# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 565)
        MainWindow.setMinimumSize(QtCore.QSize(980, 565))
        MainWindow.setMaximumSize(QtCore.QSize(980, 565))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 30, 913, 433))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_textEdit = QtWidgets.QTextEdit(self.widget)
        self.name_textEdit.setMinimumSize(QtCore.QSize(391, 31))
        self.name_textEdit.setMaximumSize(QtCore.QSize(391, 31))
        self.name_textEdit.setObjectName("name_textEdit")
        self.verticalLayout.addWidget(self.name_textEdit)
        self.open_pushButton = QtWidgets.QPushButton(self.widget)
        self.open_pushButton.setMinimumSize(QtCore.QSize(391, 31))
        self.open_pushButton.setMaximumSize(QtCore.QSize(391, 31))
        self.open_pushButton.setObjectName("open_pushButton")
        self.verticalLayout.addWidget(self.open_pushButton)
        self.create_pushButton = QtWidgets.QPushButton(self.widget)
        self.create_pushButton.setMinimumSize(QtCore.QSize(391, 31))
        self.create_pushButton.setMaximumSize(QtCore.QSize(391, 31))
        self.create_pushButton.setObjectName("create_pushButton")
        self.verticalLayout.addWidget(self.create_pushButton)
        self.save_pushButton = QtWidgets.QPushButton(self.widget)
        self.save_pushButton.setMinimumSize(QtCore.QSize(391, 31))
        self.save_pushButton.setMaximumSize(QtCore.QSize(391, 31))
        self.save_pushButton.setObjectName("save_pushButton")
        self.verticalLayout.addWidget(self.save_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.show_textEdit = QtWidgets.QTextEdit(self.widget)
        self.show_textEdit.setMinimumSize(QtCore.QSize(511, 431))
        self.show_textEdit.setMaximumSize(QtCore.QSize(511, 431))
        self.show_textEdit.setObjectName("show_textEdit")
        self.horizontalLayout.addWidget(self.show_textEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Текстовый редактор"))
        self.open_pushButton.setText(_translate("MainWindow", "Открыть файл"))
        self.create_pushButton.setText(_translate("MainWindow", "Создать файл"))
        self.save_pushButton.setText(_translate("MainWindow", "Сохранить изменения в файле"))
