# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 650)
        Form.setMinimumSize(QtCore.QSize(580, 650))
        Form.setMaximumSize(QtCore.QSize(580, 650))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 561, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.coefficient_label = QtWidgets.QLabel(self.widget)
        self.coefficient_label.setMinimumSize(QtCore.QSize(30, 20))
        self.coefficient_label.setMaximumSize(QtCore.QSize(30, 20))
        self.coefficient_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coefficient_label.setObjectName("coefficient_label")
        self.horizontalLayout.addWidget(self.coefficient_label)
        self.coeff_text = QtWidgets.QTextEdit(self.widget)
        self.coeff_text.setObjectName("coeff_text")
        self.horizontalLayout.addWidget(self.coeff_text)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.repeat_count_label = QtWidgets.QLabel(self.widget)
        self.repeat_count_label.setMinimumSize(QtCore.QSize(30, 20))
        self.repeat_count_label.setMaximumSize(QtCore.QSize(30, 20))
        self.repeat_count_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.repeat_count_label.setObjectName("repeat_count_label")
        self.horizontalLayout_2.addWidget(self.repeat_count_label)
        self.repeat_count_text = QtWidgets.QTextEdit(self.widget)
        self.repeat_count_text.setObjectName("repeat_count_text")
        self.horizontalLayout_2.addWidget(self.repeat_count_text)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.show_button = QtWidgets.QPushButton(self.widget)
        self.show_button.setMinimumSize(QtCore.QSize(100, 40))
        self.show_button.setMaximumSize(QtCore.QSize(100, 40))
        self.show_button.setObjectName("show_button")
        self.horizontalLayout_3.addWidget(self.show_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.coefficient_label.setText(_translate("Form", "K ="))
        self.repeat_count_label.setText(_translate("Form", "N ="))
        self.show_button.setText(_translate("Form", "Рисовать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
