# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui131.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 650)
        MainWindow.setMinimumSize(QtCore.QSize(580, 650))
        MainWindow.setMaximumSize(QtCore.QSize(580, 650))
        self.layoutWidget = QtWidgets.QWidget(MainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 561, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.widgets = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.widgets.setContentsMargins(0, 0, 0, 0)
        self.widgets.setObjectName("widgets")
        self.Buttons = QtWidgets.QVBoxLayout()
        self.Buttons.setObjectName("Buttons")
        self.show_button = QtWidgets.QPushButton(self.layoutWidget)
        self.show_button.setMinimumSize(QtCore.QSize(200, 60))
        self.show_button.setMaximumSize(QtCore.QSize(200, 60))
        self.show_button.setObjectName("show_button")
        self.Buttons.addWidget(self.show_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Buttons.addItem(spacerItem)
        self.widgets.addLayout(self.Buttons)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.widgets.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.side = QtWidgets.QLabel(self.layoutWidget)
        self.side.setMinimumSize(QtCore.QSize(60, 10))
        self.side.setMaximumSize(QtCore.QSize(60, 30))
        self.side.setObjectName("side")
        self.verticalLayout_2.addWidget(self.side)
        self.coefficient_label = QtWidgets.QLabel(self.layoutWidget)
        self.coefficient_label.setMinimumSize(QtCore.QSize(60, 10))
        self.coefficient_label.setMaximumSize(QtCore.QSize(60, 30))
        self.coefficient_label.setObjectName("coefficient_label")
        self.verticalLayout_2.addWidget(self.coefficient_label)
        self.repeat_count_label = QtWidgets.QLabel(self.layoutWidget)
        self.repeat_count_label.setMinimumSize(QtCore.QSize(60, 10))
        self.repeat_count_label.setMaximumSize(QtCore.QSize(60, 30))
        self.repeat_count_label.setObjectName("repeat_count_label")
        self.verticalLayout_2.addWidget(self.repeat_count_label)
        self.widgets.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.side_text = QtWidgets.QTextEdit(self.layoutWidget)
        self.side_text.setObjectName("side_text")
        self.verticalLayout.addWidget(self.side_text)
        self.coefficient_text = QtWidgets.QTextEdit(self.layoutWidget)
        self.coefficient_text.setObjectName("coefficient_text")
        self.verticalLayout.addWidget(self.coefficient_text)
        self.repeat_count_text = QtWidgets.QTextEdit(self.layoutWidget)
        self.repeat_count_text.setObjectName("repeat_count_text")
        self.verticalLayout.addWidget(self.repeat_count_text)
        self.widgets.addLayout(self.verticalLayout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.show_button.setText(_translate("MainWindow", "Показать"))
        self.side.setText(_translate("MainWindow", "side"))
        self.coefficient_label.setText(_translate("MainWindow", "coeff"))
        self.repeat_count_label.setText(_translate("MainWindow", "n"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
